import os
import subprocess
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    # SCons injects these at runtime. Declare stubs for IDEs/type-checkers.
    def Import(name: str) -> None: ...
    env: Any
else:
    # NOTE: This script is executed by PlatformIO/SCons.
    # - `Import` and `env` are injected by SCons at runtime.
    # - The stubs/guards below keep IDEs/type-checkers quiet without changing behavior.
    env: Any = None
    try:
        Import("env")  # type: ignore[name-defined]  # noqa: F821
    except NameError:
        pass

FLASH_TOTAL = 30720  # 30 KB usable after bootloader
SRAM_TOTAL = 2048
EEPROM_TOTAL = 1024

FLASH_LIMIT = 25500  # 85% of 30 KB
SRAM_LIMIT = 1740    # 85% of 2 KB
EEPROM_LIMIT = 870   # 85% of 1 KB

FLASH_WARN = 23040   # 75% of 30 KB
SRAM_WARN = 1536     # 75% of 2 KB

EEPROM_USED = 512    # Bytes reserved by our EEPROM map (Appendix D)

def _enable_linker_map():
    # Always emit a linker MAP file for size profiling.
    # This is a no-op when not running under PlatformIO/SCons.
    if env is None:
        return
    build_dir = env.subst("$BUILD_DIR")
    progname = env.subst("${PROGNAME}")
    map_path = os.path.join(build_dir, f"{progname}.map")
    env.Append(LINKFLAGS=[f"-Wl,-Map,{map_path}"])


def _move_flag_to_cxx_only(flag):
    # PlatformIO applies build_flags to both C and C++. Some flags are C++-only
    # (e.g., -fno-rtti) and will emit warnings for C sources. Move them to
    # CXXFLAGS so we still get the intended size savings without noisy builds.
    if env is None:
        return
    for key in ("CCFLAGS", "CFLAGS"):
        if key in env:
            env[key] = [f for f in env[key] if f != flag]
    env.Append(CXXFLAGS=[flag])


_move_flag_to_cxx_only("-fno-rtti")
_move_flag_to_cxx_only("-fno-exceptions")
if env is not None:
    env.Append(CXXFLAGS=["-fno-threadsafe-statics"])
    _enable_linker_map()


def _write_generated_header(project_dir, flash_used, sram_used):
    out_dir = os.path.join(project_dir, "include", "generated")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "build_memory.h")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("\n")
        f.write("// Auto-generated by check_memory.py (do not commit)\n")
        f.write(f"#define BUILD_FLASH_USED_BYTES {flash_used}\n")
        f.write(f"#define BUILD_FLASH_TOTAL_BYTES {FLASH_TOTAL}\n")
        f.write(f"#define BUILD_SRAM_USED_BYTES {sram_used}\n")
        f.write(f"#define BUILD_SRAM_TOTAL_BYTES {SRAM_TOTAL}\n")
        f.write(f"#define BUILD_EEPROM_USED_BYTES {EEPROM_USED}\n")
        f.write(f"#define BUILD_EEPROM_TOTAL_BYTES {EEPROM_TOTAL}\n")


def _parse_avr_size_output(stdout_text):
    flash_used = None
    sram_used = None

    for raw_line in stdout_text.splitlines():
        line = raw_line.strip()
        if line.startswith("Program:"):
            parts = line.split()
            if len(parts) >= 2:
                flash_used = int(parts[1])
        elif line.startswith("Data:"):
            parts = line.split()
            if len(parts) >= 2:
                sram_used = int(parts[1])

    return flash_used, sram_used


def check_memory_usage(source, target, env):
    firmware_path = str(target[0])
    project_dir = env.get("PROJECT_DIR", ".")

    size_tool = env.get("SIZE", "avr-size")
    mcu = env.BoardConfig().get("build.mcu", "atmega328p")

    result = subprocess.run(
        [size_tool, "-C", f"--mcu={mcu}", firmware_path],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("\n" + ("=" * 50))
        print("ERROR: avr-size failed")
        print(result.stderr)
        print(("=" * 50) + "\n")
        env.Exit(1)

    flash_used, sram_used = _parse_avr_size_output(result.stdout)
    if flash_used is None or sram_used is None:
        print("\n" + ("=" * 50))
        print("ERROR: Failed to parse avr-size output")
        print(result.stdout)
        print(("=" * 50) + "\n")
        env.Exit(1)

    flash_percent = (flash_used / FLASH_TOTAL) * 100.0
    sram_percent = (sram_used / SRAM_TOTAL) * 100.0
    eeprom_percent = (EEPROM_USED / EEPROM_TOTAL) * 100.0

    print("\n" + ("=" * 50))
    print("FLASH MEMORY USAGE:")
    print(f"  Used:  {flash_used} bytes ({flash_percent:.1f}%)")
    print(f"  Limit: {FLASH_LIMIT} bytes (85.0%)")
    print(f"  Total: {FLASH_TOTAL} bytes")

    if flash_used > FLASH_LIMIT:
        print("  ❌ FLASH USAGE EXCEEDS LIMIT!")
        env.Exit(1)
    elif flash_used > FLASH_WARN:
        print("  ⚠️  WARNING: Flash usage >75%")
    else:
        print("  ✅ Flash usage OK")

    print("\nSRAM USAGE:")
    print(f"  Used:  {sram_used} bytes ({sram_percent:.1f}%)")
    print(f"  Limit: {SRAM_LIMIT} bytes (85.0%)")
    print(f"  Total: {SRAM_TOTAL} bytes")

    if sram_used > SRAM_LIMIT:
        print("  ❌ SRAM USAGE EXCEEDS LIMIT!")
        env.Exit(1)
    elif sram_used > SRAM_WARN:
        print("  ⚠️  WARNING: SRAM usage >75%")
    else:
        print("  ✅ SRAM usage OK")

    print("\nEEPROM USAGE (reserved map):")
    print(f"  Used:  {EEPROM_USED} bytes ({eeprom_percent:.1f}%)")
    print(f"  Limit: {EEPROM_LIMIT} bytes (85.0%)")
    print(f"  Total: {EEPROM_TOTAL} bytes")

    if EEPROM_USED > EEPROM_LIMIT:
        print("  ❌ EEPROM USAGE EXCEEDS LIMIT!")
        env.Exit(1)
    else:
        print("  ✅ EEPROM usage OK")

    print(("=" * 50) + "\n")

    _write_generated_header(project_dir, flash_used, sram_used)

    # Optional: print top symbols for quick triage.
    try:
        enabled = str(env.GetProjectOption("custom_size_profile", "0")).strip() == "1"
    except Exception:
        enabled = False

    if enabled:
        nm_tool = env.get("NM", "avr-nm")
        try:
            nm = subprocess.run(
                [nm_tool, "-S", "--size-sort", "-r", "-t", "dec", "-C", firmware_path],
                capture_output=True,
                text=True,
            )
            if nm.returncode == 0 and nm.stdout:
                print("TOP SYMBOLS (largest first):")
                # Filter to "real" symbols (text/data/bss/rodata) to avoid debug section noise.
                keep_types = set("tTwWdDbBrRvV")
                printed = 0
                for raw in nm.stdout.splitlines():
                    ln = raw.strip()
                    if not ln:
                        continue
                    parts = ln.split(None, 3)
                    if len(parts) < 4:
                        continue
                    sym_type = parts[2]
                    if sym_type and sym_type[0] in keep_types:
                        print("  " + ln)
                        printed += 1
                        if printed >= 30:
                            break
                print()
            else:
                print("NOTE: avr-nm size profile unavailable")
        except Exception:
            print("NOTE: avr-nm size profile failed")


if env is not None:
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.elf", check_memory_usage)
